### PR TITLE
Use Bootstrap with scss

### PR DESCRIPTION
**Pull request by obar**
Rather than include all of Bootstrap css pre-minified, this uses hugo pipes (requires hugo extended) to process Bootstrap from scss. It lets the user adjust the theme more powerfully using variables, and allows for excluding parts of Bootstrap that aren't used.

Example customization is included to show changing the `$primary` color (note link color across site) as well as the style for `.blockquote`, compare the "Quotes by Carl Jung" post. The former demonstrates the power of variables, the latter is the same sort of customization that is possible normally.

### CODE REVIEW

**Comment by zwbetz-gh** [comment]
Thank you for this PR. Although I like your changes, and I think some theme users would like them as well, it cuts off a portion of theme users who do not run the extended version of Hugo. 

Have a good one. Closing this.

**Comment by obar** [comment]
I believe there used to be a cost to running hugo extended, in that it wasn't available everywhere. It's now available in web hosting environments [like netlify](https://www.netlify.com/blog/2019/03/14/a-more-flexible-build-architecture-with-updated-linux/) though and pipes are very clearly the direction things are headed.

That said, I'm new to using hugo so may be missing some other points. Is there anything else that would stop someone from using hugo extended?

**Comment by zwbetz-gh** [comment]
> I believe there used to be a cost to running hugo extended, in that it wasn't available everywhere. It's now available in web hosting environments like netlify though and pipes are very clearly the direction things are headed.

Correct 👍 

**But**, users on a 32-bit OS cannot run Hugo extended. Yes, this is a small fraction of users, but I want to keep my themes as accessible as possible.

**Comment by obar** [comment]
TIL :) Thanks!

**Pull request closed without merging**
