### PR TITLE
undraft homepage

### PR DESCRIPTION
**Pull request by apreshill**
Hoping this saves someone else time! Not sure if there was a reason this was set as a draft.

### CODE REVIEW

**Comment by zwbetz-gh** [comment]
Hi @apreshill, thanks for the PR. So this is actually on purpose. 

If the theme [sees you have a homepage](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme/blob/62db2fea6a773b4e9f835de1cd406dbb6b611f38/layouts/index.html#L4-L6) then it will show that. Else, it will show [`.Site.Params.homeText`](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme/blob/62db2fea6a773b4e9f835de1cd406dbb6b611f38/layouts/index.html#L7-L9). 

Now, if you think the README could explain that better, then I'm open to suggestions.

**Comment by apreshill** [comment]
Ah I see that now! I guess it is a bit tricky though since as is, the example site won't work "out of the box"? I.e., in the example site this is not blank:

```
params:
  homeText: Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream.
```

and yet, the example site was empty on Netlify (built successfully, able to preview locally, just nothing there to deploy!). I finally figured out that `_index.md` had draft set to true, but it was surprising. So it seems like the layout file needs to ignore the page title of `_index.md` not just if the page does not exists, but ALSO if it is not a draft too? B/c with the exampleSite as is, it correctly detects the presence of that file, but there is no site.

**Comment by apreshill** [comment]
i.e., here was my first naive attempt to deploy the exampleSite: 

https://app.netlify.com/sites/confident-lewin-c44a96/deploys/602d5f2db686c91a23ad2522
https://602d5f2db686c91a23ad2522--confident-lewin-c44a96.netlify.app/

**Comment by zwbetz-gh** [comment]
Hmm, good question. Going to play with this more tonight then get back to
you.

**Comment by apreshill** [comment]
[deploy-602d617142c9110008bdca52.zip](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme/files/5998186/deploy-602d617142c9110008bdca52.zip)

Here was the zip I downloaded from Netlify when I started to get a clue of at least what went wrong

**Comment by zwbetz-gh** [comment]
What does your netlify config look like?

This is how I deploy the theme example site https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme/blob/master/netlify.toml

**Comment by apreshill** [comment]
I use an R package to install the theme, so the exampleSite contents get moved into the root. Here was the site's netlify.toml file:

https://github.com/apreshill/qbert/blame/vanilla/netlify.toml

And the site when I first deployed (forgot to ignore public and resources, but you get the drift):
https://github.com/apreshill/qbert/tree/30d70c92c4d6d22636828ff394a58ae2eb663ba0

(A write-up of the workflow here using the Wowchemy theme: https://alison.rbind.io/post/new-year-new-blogdown/)

**Comment by zwbetz-gh** [comment]
Unfortunately those first 2 github links give me a 404

**Comment by apreshill** [comment]
Ack sorry- forgot it was private. Made it public.

**Comment by zwbetz-gh** [comment]
Okay can view them now. And so that I can understand better -- Are you wanting to deploy the example site of the theme? Or, do you want to use the theme as usual, with your own content?

**Comment by apreshill** [comment]
I started with the example site, then started editing existing files first. If you have any users who work with the blogdown package in R, when you create a new site from a theme, there is an argument to copy the exampleSite over to the root so you can work by editing, which is what I always do/teach.

**Comment by zwbetz-gh** [comment]
That makes sense to me. And now I am on the same page.

Here's what I did to replicate. After doing these steps, the served site was indeed blank until I set the homepage as `draft: false`

Will merge your change, then will make a subsequent change to docs to clear this up. Thank you @apreshill 

```shell
# Create a new site
hugo new site vanilla-test

# Change to it
cd vanilla-test/

# Init as a git repo
git init

# Add the vanilla theme as a submodule
git submodule add https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme.git themes/vanilla-bootstrap-hugo-theme

# Copy the example site to the root
cp -r themes/vanilla-bootstrap-hugo-theme/exampleSite/ .

# Serve it
hugo server
```

**Pull request merged**
